# Generated by Django 2.0.13 on 2019-06-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outstationroute', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outstationroutepage',
            name='excerpt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
