# Generated by Django 2.0.13 on 2019-07-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outstationroute', '0002_auto_20190626_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outstationroutepage',
            name='robots_tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
