# Generated by Django 2.0.13 on 2019-07-12 10:04

from django.db import migrations
import outstation.apps.framework.fields


class Migration(migrations.Migration):

    dependencies = [
        ('outstationroute', '0003_auto_20190704_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='outstationroutepage',
            name='banner_title_2',
            field=outstation.apps.framework.fields.RichCharField(max_length=255, null=True),
        ),
    ]
