# Generated by Django 2.0.13 on 2019-07-12 10:29

from django.db import migrations
import outstation.apps.framework.fields


class Migration(migrations.Migration):

    dependencies = [
        ('outstationroute', '0004_outstationroutepage_banner_title_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outstationroutepage',
            name='banner_title_2',
            field=outstation.apps.framework.fields.RichCharField(max_length=10, null=True),
        ),
    ]
