# Generated by Django 2.0.13 on 2019-07-12 10:43

from django.db import migrations
import outstation.apps.framework.fields


class Migration(migrations.Migration):

    dependencies = [
        ('outstationroute', '0006_auto_20190712_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outstationroutepage',
            name='banner_title_2',
        ),
        migrations.AlterField(
            model_name='outstationroutepage',
            name='banner_title',
            field=outstation.apps.framework.fields.RichCharField(max_length=255, null=True),
        ),
    ]
