# Generated by Django 2.0.13 on 2019-07-12 12:05

from django.db import migrations
import outstation.apps.framework.fields


class Migration(migrations.Migration):

    dependencies = [
        ('outstationroute', '0007_auto_20190712_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outstationroutepage',
            name='destination_display_name',
            field=outstation.apps.framework.fields.RichCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='outstationroutepage',
            name='origin_display_name',
            field=outstation.apps.framework.fields.RichCharField(blank=True, max_length=255, null=True),
        ),
    ]
