# Generated by Django 2.1.8 on 2019-08-30 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outstationroute', '0009_outstationroutepage_customized_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outstationroutepage',
            name='customized_map',
        ),
    ]
