# Generated by Django 2.1.8 on 2019-09-15 17:38

from django.db import migrations, models
import outstation.apps.core.enums


class Migration(migrations.Migration):

    dependencies = [
        ('outstationreview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(default=outstation.apps.core.enums.ReviewStatusChoice('NEW'), max_length=20),
        ),
    ]
