# Generated by Django 2.1.8 on 2019-09-15 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outstationreview', '0003_auto_20190915_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='status',
        ),
    ]
