# Generated by Django 2.1.8 on 2019-09-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outstationreview', '0004_remove_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(default='new', max_length=20),
        ),
    ]
