# Generated by Django 2.1.8 on 2019-09-15 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outstationreview', '0005_review_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='status',
        ),
    ]
