# Generated by Django 2.1.8 on 2019-09-30 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outstationframework', '0001_initial'),
        ('outstationreview', '0007_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='outstationframework.AdvancedImage'),
        ),
    ]
