# Generated by Django 2.0.13 on 2019-06-22 07:48

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import outstation.apps.core.enums
import wagtail.search.index


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='FareTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('HATCHBACK', 'HATCHBACK'), ('SEDAN', 'SEDAN'), ('SUV', 'SUV'), ('MINIBUS', 'MINIBUS'), ('SEDAN - PREMIUM', 'SEDAN - PREMIUM'), ('SEDAN - BUSINEESS CLASS', 'SEDAN - BUSINESS'), ('LUXURY', 'LUXURY')], default=outstation.apps.core.enums.VehicleTypeChoice('HATCHBACK'), max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('seater', models.PositiveSmallIntegerField(default=0)),
                ('per_km_rate', models.PositiveSmallIntegerField(default=0, verbose_name='Per km rate (₹)')),
                ('vehicle_feature', models.CharField(choices=[('AC', 'AC'), ('Non AC', 'NON - AC')], default=outstation.apps.core.enums.VehicleFeatureChoice('AC'), max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Fares',
                'verbose_name': 'Fare',
            },
        ),
        migrations.CreateModel(
            name='LocationTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(help_text='Location tag', max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Location Tags',
                'verbose_name': 'Location Tag',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('details', models.TextField(help_text='Add place details')),
                ('duration_of_visit', models.DurationField(blank=True, default='00:00:00', help_text='[DD] [HH:[MM:]]ss[.uuuuuu] format', null=True, verbose_name='Duration Of Visit (HH:MM:SS)')),
                ('location_tags', modelcluster.fields.ParentalManyToManyField(to='outstationcore.LocationTag')),
                ('map_icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='PlaceImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image')),
                ('place', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_images', to='outstationcore.Place')),
            ],
        ),
        migrations.CreateModel(
            name='PopularRoutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=200, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Popular Routes',
                'verbose_name': 'Popular Route',
            },
        ),
        migrations.CreateModel(
            name='RouteLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('url', models.URLField()),
                ('popular_route', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_routes', to='outstationcore.PopularRoutes')),
            ],
        ),
        migrations.CreateModel(
            name='TripType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_type', models.CharField(help_text='Trip type', max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Trip Types',
                'verbose_name': 'Trip Type',
            },
        ),
        migrations.AddField(
            model_name='place',
            name='trip_types',
            field=modelcluster.fields.ParentalManyToManyField(to='outstationcore.TripType'),
        ),
        migrations.AlterUniqueTogether(
            name='routelink',
            unique_together={('popular_route', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='placeimages',
            unique_together={('place', 'image')},
        ),
    ]
