# Generated by Django 2.0.13 on 2019-07-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outstationcore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faretable',
            name='model',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='locationtag',
            name='tag',
            field=models.CharField(help_text='Location tag', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='popularroutes',
            name='region',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='routelink',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='triptype',
            name='trip_type',
            field=models.CharField(help_text='Trip type', max_length=255, unique=True),
        ),
    ]
